name: Build Society Pro
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version-file: ${{ github.workspace }}/.python-version

      - name: Setup uv
        uses: yezz123/setup-uv@v4.1
        with:
          uv-venv: ${{ github.workspace }}/.venv

      - name: UV sync
        run: uv sync

      - name: Build project with nuitka
        run: |
          chmod +x ${{ github.workspace }}/build_nuitka.sh
          ${{ github.workspace }}/build_nuitka.sh
          
      - name: SemVer Autotag
        id: autotag
        uses: DanySK/semver-autotag-action@0.1.0
      
      - name: Push Tag to Remote
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@://github.com:${{ github.repository }}.git
          git push origin --tags
  
      - name: Get Version
        id: vars
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
  
      - name: Package Binaries
        run: |
          # Create a Zip archive
          zip -r society-membership-v${{ steps.vars.outputs.tag }}.zip ./build/society-membership.dist/
          
      - name: Create Release and Upload Archives
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release create ${{ steps.vars.outputs.tag }} \
            --title "Society Pro ${{ steps.vars.outputs.tag }}" \
            --generate-notes \
            society-membership-v${{ steps.vars.outputs.tag }}.zip
