name: Build Society Pro
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version-file: ${{ github.workspace }}/.python-version

      - name: Setup uv
        uses: yezz123/setup-uv@v4.1
        with:
          uv-venv: .venv

      - name: UV sync
        run: uv sync

      - name: Build project with nuitka
        run: |
          chmod +x ${{ github.workspace }}/build_nuitka.sh
          ${{ github.workspace }}/build_nuitka.sh

      - name: Python Semantic Release - Publish
        uses: python-semantic-release/publish-action@v10.5.3
        with:
          config_file: pyproject.toml
          directory: ${{ github.workspace }}
          github_token: ${{ secrets.GH_TOKEN }}
